version: 3

pullapprove_conditions:
- condition: "'WIP' not in title"
  unmet_status: pending
  explanation: "Work in progress"

groups:
  code-review:
    reviews:
      required: 1
    reviewers:
      teams:
      - core-maintainers
