files:
  - source: /bundles/**/i18n/**/*.properties
    ignore:
      - /bundles/**/i18n/**/*_*.properties
    translation: /%original_path%/%file_name%_%two_letters_code%.properties
  - source: /bundles/**/src/main/resources/*.properties
    ignore:
      - /bundles/**/src/main/resources/*_*.properties
    translation: /%original_path%/messages_%two_letters_code%.properties
