/*
 * Copyright (c) 2010-2026 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.core.voice.text.conversation;

import org.eclipse.jdt.annotation.NonNullByDefault;

/**
 * The {@link ConversationRole} class defines the role/author of a message in a {@link Conversation}.
 *
 * @author Miguel Álvarez Díez - Initial contribution
 */
@NonNullByDefault
public enum ConversationRole {
    /** For user messages **/
    USER,
    /** For messages generated by an interpreter **/
    OPENHAB,
    /** For LLM thinking **/
    THINKING,
    /** For LLM tool calling **/
    TOOL_CALL,
    /** For LLM tool call calling result **/
    TOOL_RETURN
}
