/*
 * Copyright (c) 2010-2026 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.core.model.yaml.internal.util.preprocessor;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.ZonedDateTime;
import java.util.Map;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;
import org.openhab.core.OpenHAB;
import org.openhab.core.model.yaml.internal.util.preprocessor.constructor.ModelConstructor;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.LoaderOptions;
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.representer.Representer;

/**
 * Pure utility functions for YAML preprocessing.
 *
 * @author Jimmy Tanagra - Initial contribution
 */
@NonNullByDefault
final class PreprocessorUtils {

    private PreprocessorUtils() {
        // Static utility class
    }

    /**
     * Removes top-level keys that start with a dot from the given map.
     *
     * @param dataMap the map to process
     */
    static void removeHiddenKeys(Map<?, ?> dataMap) {
        dataMap.keySet().removeIf(key -> key instanceof String keyStr && keyStr.startsWith("."));
    }

    /**
     * Writes the fully processed YAML representation as it would be seen by openHAB after preprocessing
     * to a compiled output file.
     *
     * @param dataMap the resulting data map to dump
     * @param context the preprocessor context containing paths and logs
     * @throws IOException if writing to the file fails
     */
    static void writeCompiledOutput(Object dataMap, PreprocessorContext context) throws IOException {
        Path absolutePath = context.getAbsolutePath();
        Path relativePath = context.getRelativePath();

        Path outputFile = PreprocessorConfig.resolveCompiledOutputPath(absolutePath, relativePath);

        Path outputDir = outputFile.getParent();
        if (outputDir != null) {
            Files.createDirectories(outputDir);
        }

        DumperOptions dumperOptions = new DumperOptions();
        dumperOptions.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        dumperOptions.setIndentWithIndicator(true);
        dumperOptions.setIndicatorIndent(2);
        dumperOptions.setPrettyFlow(true);

        Yaml yaml = new Yaml(dumperOptions);
        String compiledYaml = yaml.dump(dataMap);

        compiledYaml = """
                # ==============================================================================
                # Generated by openHAB %s (%s) YAML Preprocessor, DO NOT EDIT
                # Source:    %s
                # Generated: %s
                # ==============================================================================
                                """.strip().formatted(OpenHAB.getVersion(), OpenHAB.buildString(), relativePath,
                ZonedDateTime.now()) + "\n" + compiledYaml;

        Files.writeString(outputFile, compiledYaml, StandardCharsets.UTF_8);
        context.getLogger().info("YAML model {}: Generated compiled YAML output to {}", relativePath, outputFile);
    }

    /**
     * Creates a new SnakeYAML instance with the custom preprocessor constructor and resolver.
     *
     * @param sourcePath the source path of the YAML file for error reporting in the constructor
     * @return a new Yaml instance
     */
    static Yaml createYaml(String sourcePath) {
        LoaderOptions loaderOptions = new LoaderOptions();
        loaderOptions.setAllowDuplicateKeys(false);
        return new Yaml(new ModelConstructor(loaderOptions, sourcePath), new Representer(new DumperOptions()),
                new DumperOptions(), loaderOptions, new StrictBooleanResolver());
    }

    /**
     * Loads YAML content from the given byte array using a Yaml instance configured with the custom constructor.
     *
     * @param fileBytes the YAML content as a byte array
     * @param sourcePath the source path of the YAML file for error reporting in the constructor
     * @return the loaded YAML object
     * @throws IOException if an I/O error occurs
     */
    static @Nullable Object loadYaml(byte[] fileBytes, Path sourcePath) throws IOException {
        Yaml yaml = createYaml(sourcePath.toString());
        return yaml.load(new ByteArrayInputStream(fileBytes));
    }
}
