/*
 * Copyright (c) 2010-2026 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.core.auth;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Date;
import java.util.Objects;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An API token represents long-term credentials generated by (or for) a user, giving the bearer access for a certain
 * scope on behalf of this user. This class doesn't store the token itself, but the hashed token and the salt.
 *
 * @author Yannick Schaus - initial contribution
 */
@NonNullByDefault
@JsonAdapter(UserApiToken.AdapterFactory.class)
public class UserApiToken {
    private final String name;
    private final byte[] tokenSalt;
    private final String tokenHash;
    private final Date createdTime;
    private final String scope;

    /**
     * Constructs an API token.
     *
     * @param name the name of the token, for identification purposes.
     * @param tokenHash the hash of the token using the specified salt.
     * @param salt the salt used to hash the token.
     * @param scope the scope this token is valid for.
     */
    public UserApiToken(String name, String tokenHash, byte[] salt, String scope) {
        this(name, tokenHash, salt, new Date(), scope);
    }

    /**
     * Constructs an API token. For deserialization use only.
     *
     * @param name the name of the token, for identification purposes.
     * @param tokenHash the hash of the token using the specified salt.
     * @param salt the salt used to hash the token.
     * @param createdTime the {@link Date} indicating when the token was created.
     * @param scope the scope this token is valid for.
     */
    UserApiToken(String name, String tokenHash, byte[] salt, Date createdTime, String scope) {
        this.name = name;
        this.tokenHash = tokenHash;
        this.tokenSalt = Arrays.copyOf(salt, salt.length);
        this.createdTime = createdTime;
        this.scope = scope;
    }

    /**
     * Constructs an API token.
     *
     * @deprecated Use {@link UserApiToken#UserApiToken(String, String, byte[], String)} instead.
     *
     * @param name the name of the token, for identification purposes.
     * @param apiToken the hashed token and the salt separated by {@code ':'}.
     * @param scope the scope this token is valid for.
     */
    @Deprecated
    public UserApiToken(String name, String apiToken, String scope) {
        this(name, apiToken, new Date(), scope);
    }

    /**
     * Constructs an API token. For deserialization use only.
     *
     * @param name the name of the token, for identification purposes.
     * @param apiToken the hashed token and the salt separated by {@code ':'}.
     * @param createdTime the {@link Date} indicating when the token was created.
     * @param scope the scope this token is valid for.
     */
    UserApiToken(String name, String apiToken, Date createdTime, String scope) {
        this.name = name;
        String[] hashAndSalt = apiToken.split(":");
        this.tokenHash = hashAndSalt[0];
        this.tokenSalt = hashAndSalt.length > 1 ? hashAndSalt[1].getBytes(StandardCharsets.UTF_8) : new byte[0];
        this.createdTime = createdTime;
        this.scope = scope;
    }

    /**
     * Gets the name identifying the token
     *
     * @return the API token
     */
    public String getName() {
        return name;
    }

    /**
     * Get the hashed API token.
     *
     * @return The hashed API token.
     */
    public String getTokenHash() {
        return tokenHash;
    }

    /**
     * Get the salt used to hash the token.
     *
     * @return The salt.
     */
    public byte[] getSalt() {
        return Arrays.copyOf(tokenSalt, tokenSalt.length);
    }

    /**
     * Get the hashed API token and the salt, separated by a {@code ':'}.
     *
     * @deprecated Use {@link #getTokenHash()} and {@link #getSalt()} instead.
     *
     * @return the hashed API token and salt.
     */
    @Deprecated
    public String getApiToken() {
        return tokenHash + ':' + new String(tokenSalt, StandardCharsets.UTF_8);
    }

    /**
     * Gets the time when this token was created.
     *
     * @return the date of creation
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * Gets the scope this token is valid for.
     *
     * @return the scope
     */
    public String getScope() {
        return scope;
    }

    @Override
    public String toString() {
        return "name=" + name + ", createdTime=" + createdTime + ", scope=" + scope;
    }

    public static class AdapterFactory implements TypeAdapterFactory {
        @Override
        public @Nullable <T> TypeAdapter<T> create(@Nullable Gson gson, @Nullable TypeToken<T> type) {
            if (gson == null || type == null || !UserApiToken.class.isAssignableFrom(type.getRawType())) {
                return null;
            }

            @SuppressWarnings("unchecked")
            final TypeAdapter<UserApiToken> delegateAdapter = (TypeAdapter<UserApiToken>) gson.getDelegateAdapter(this,
                    type);
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            return new TypeAdapter<T>() {

                @Override
                public void write(JsonWriter out, T value) throws IOException {
                    delegateAdapter.write(out, (UserApiToken) value);
                }

                @Override
                public @Nullable T read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);

                    // Custom read logic for the old format
                    if (jsonElement instanceof JsonObject jsonObject && jsonObject.has("apiToken")
                            && !jsonObject.has("tokenHash")) {
                        String name = jsonObject.get("name").getAsString();
                        String scope = jsonObject.has("scope") ? jsonObject.get("scope").getAsString() : "";
                        Date createdTime = Objects
                                .requireNonNull(gson.fromJson(jsonObject.get("createdTime"), Date.class));
                        String legacyApiToken = jsonObject.get("apiToken").getAsString();

                        @SuppressWarnings("unchecked")
                        T result = (T) new UserApiToken(name, legacyApiToken, createdTime, scope);
                        return result;
                    }

                    // Fall back to default adapter
                    if (jsonElement == null) {
                        return null;
                    }
                    @SuppressWarnings("unchecked")
                    T result = (T) delegateAdapter.fromJsonTree(jsonElement);
                    return result;
                }
            };
        }
    }
}
