/*
 * Copyright (c) 2010-2026 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.core.auth;

import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Date;

import org.eclipse.jdt.annotation.NonNullByDefault;

/**
 * An API token represents long-term credentials generated by (or for) a user, giving the bearer access for a certain
 * scope on behalf of this user. This class doesn't store the token itself, but the hashed token and the salt.
 *
 * @author Yannick Schaus - initial contribution
 */
@NonNullByDefault
public class UserApiToken {
    private final String name;
    private final byte[] tokenSalt;
    private final String tokenHash;
    private final Date createdTime;
    private final String scope;

    /**
     * Constructs an API token.
     *
     * @param name the name of the token, for identification purposes.
     * @param tokenHash the hash of the token using the specified salt.
     * @param salt the salt used to hash the token.
     * @param scope the scope this token is valid for.
     */
    public UserApiToken(String name, String tokenHash, byte[] salt, String scope) {
        this.name = name;
        this.tokenHash = tokenHash;
        this.tokenSalt = Arrays.copyOf(salt, salt.length);
        this.createdTime = new Date();
        this.scope = scope;
    }

    /**
     * Constructs an API token.
     *
     * @deprecated Use {@link UserApiToken#UserApiToken(String, String, byte[], String)} instead.
     *
     * @param name the name of the token, for identification purposes.
     * @param apiToken the hashed token and the salt separated by {@code ':'}.
     * @param scope the scope this token is valid for.
     */
    @Deprecated
    public UserApiToken(String name, String apiToken, String scope) {
        this.name = name;
        String[] hashAndSalt = apiToken.split(":");
        this.tokenHash = hashAndSalt[0];
        this.tokenSalt = hashAndSalt.length > 1 ? hashAndSalt[1].getBytes(StandardCharsets.UTF_8) : new byte[0];
        this.createdTime = new Date();
        this.scope = scope;
    }

    /**
     * Gets the name identifying the token
     *
     * @return the API token
     */
    public String getName() {
        return name;
    }

    /**
     * Get the hashed API token.
     *
     * @return The hashed API token.
     */
    public String getTokenHash() {
        return tokenHash;
    }

    /**
     * Get the salt used to hash the token.
     *
     * @return The salt.
     */
    public byte[] getSalt() {
        return Arrays.copyOf(tokenSalt, tokenSalt.length);
    }

    /**
     * Get the hashed API token and the salt, separated by a {@code ':'}.
     *
     * @deprecated Use {@link #getTokenHash()} and {@link #getSalt()} instead.
     *
     * @return the hashed API token and salt.
     */
    @Deprecated
    public String getApiToken() {
        return tokenHash + ':' + new String(tokenSalt, StandardCharsets.UTF_8);
    }

    /**
     * Gets the time when this token was created.
     *
     * @return the date of creation
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * Gets the scope this token is valid for.
     *
     * @return the scope
     */
    public String getScope() {
        return scope;
    }

    @Override
    public String toString() {
        return "name=" + name + ", createdTime=" + createdTime + ", scope=" + scope;
    }
}
