/*
 * Copyright (c) 2010-2026 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * generated by Xtext
 */
package org.openhab.core.model.rule.validation

import org.eclipse.emf.ecore.EObject
import org.eclipse.xtext.nodemodel.util.NodeModelUtils
import org.eclipse.xtext.validation.Check
import org.openhab.core.automation.util.RuleUtil
import org.openhab.core.model.rule.rules.Rule
import org.openhab.core.model.rule.rules.RulesPackage

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class RulesValidator extends AbstractRulesValidator {

	@Check
	def checkRuleUID(Rule rule) {
		if (rule === null || rule.uid === null) {
			return
		}
		if (!RuleUtil.isValidRuleUID(rule.uid)) {
			error(buildMsgWithLineNb(rule, "Rule UID '" + rule.uid + "' is invalid. It must consist of one or several segments separated by a colon, each segment must only contain alphanumeric, underscore or hyphen, and must not contain any other symbols."),
				rule, RulesPackage.Literals.RULE__UID)
		}
	}

	def private buildMsgWithLineNb(EObject object, String msg) {
		val node = NodeModelUtils.getNode(object)
		if (node === null) {
			return msg
		}
		val startLine = node.startLine
		val endLine = node.endLine
		if (startLine == endLine) {
			return "Line " + startLine + ": " + msg
		} else {
			return "Line " + startLine + "-" + endLine + ": " + msg
		}
	}
}
