blank_issues_enabled: true
contact_links:
  - name: 🤔 Support/Usage Question
    url: https://community.openhab.org
    about: Feel free to ask anything
  - name: 📖 Documentation
    url: https://www.openhab.org/docs/
    about: Official documentation
  - name: 📚 Translation feedback
    url: https://crowdin.com/project/openhab-core
    about: Share feedback on translations
