#!/bin/sh
#
#  Minify .png files using imageoptim.
#
#  Can be installed with NPM.
#  npm install -g imageoptim-cli
#
#  Note: The GUI application also has to be installed.
#  brew cask install imageoptim
#

if type imageoptim &>/dev/null; then

  if [ "$1" != '' ] ; then

    for file in $1*.png; do
      echo $file | imageoptim
    done

	else
		imageoptim -d "$(dirname $0)"
	fi

fi
