/*
 * Copyright (c) 2010-2026 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * generated by Xtext
 */
package org.openhab.core.model.thing.validation

import org.eclipse.emf.ecore.EAttribute
import org.eclipse.emf.ecore.EObject
import org.eclipse.xtext.nodemodel.util.NodeModelUtils
import org.eclipse.xtext.nodemodel.INode
import org.eclipse.xtext.validation.Check
import org.openhab.core.model.thing.thing.ModelThing
import org.openhab.core.model.thing.thing.ThingPackage
import org.openhab.core.thing.ThingUID

/**
 * Custom validation rules.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class ThingValidator extends AbstractThingValidator {

	@Check
	def check_thing_has_valid_id(ModelThing thing) {
		if (thing.nested) {
			// We have to provide thingTypeId and a thingId
			if (!thing.eIsSet(ThingPackage.Literals.MODEL_THING__THING_TYPE_ID)) {
				if (thing.eIsSet(ThingPackage.Literals.MODEL_PROPERTY_CONTAINER__ID)) {
					generateWarning(thing, ThingPackage.Literals.MODEL_PROPERTY_CONTAINER__ID,
						"Provide a thing type ID and a thing ID in this format: <thingTypeId> <thingId>")
				} else {
					if (thing.eIsSet(ThingPackage.Literals.MODEL_BRIDGE__BRIDGE)) {
						generateWarning(thing, ThingPackage.Literals.MODEL_BRIDGE__BRIDGE,
							"Provide a thing type ID and a thing ID in this format: <thingTypeId> <thingId>")
					}
				}
			} else {
				if (!thing.eIsSet(ThingPackage.Literals.MODEL_THING__THING_ID)) {
					generateWarning(thing, ThingPackage.Literals.MODEL_THING__THING_TYPE_ID,
						"Provide a thing type ID and a thing ID in this format: <thingTypeId> <thingId>")
				}
			}
		} else { // thing in container
			if (thing.eIsSet(ThingPackage.Literals.MODEL_THING__THING_TYPE_ID) && thing.eIsSet(ThingPackage.Literals.MODEL_THING__THING_ID)) {
				val thingTypeIdFeature = NodeModelUtils.findNodesForFeature(thing, ThingPackage.Literals.MODEL_THING__THING_TYPE_ID).head
				val thingIdFeature = NodeModelUtils.findNodesForFeature(thing, ThingPackage.Literals.MODEL_THING__THING_ID).head
				val startOffset = thingTypeIdFeature.offset
				val endOffset = thingIdFeature.endOffset
				getMessageAcceptor().acceptWarning(
					buildMsgWithLineNb(thingTypeIdFeature, thingIdFeature, "Provide a thing UID in this format: <bindingId>:<thingTypeId>:<thingId>"),
					thing, startOffset, endOffset - startOffset, null, null)
			} else {
				if (thing.id !== null) {
					try {
						new ThingUID(thing.id)
					} catch (IllegalArgumentException e) {
						generateError(thing, ThingPackage.Literals.MODEL_PROPERTY_CONTAINER__ID, e.message)
					}
				}
			}
		}
	}

	def private isNested(ModelThing thing) {
		thing.eContainingFeature == ThingPackage.Literals.MODEL_BRIDGE__THINGS
	}

	def private generateWarning(EObject object, EAttribute attribute, String msg) {
		warning(buildMsgWithLineNb(object, attribute, msg), object, attribute)
	}

	def private generateError(EObject object, EAttribute attribute, String msg) {
		error(buildMsgWithLineNb(object, attribute, msg), object, attribute)
	}

	def private buildMsgWithLineNb(EObject object, EAttribute attribute, String msg) {
		var node = NodeModelUtils.findNodesForFeature(object, attribute).head
		if (node === null) {
			node = NodeModelUtils.getNode(object)
			if (node === null) {
				return msg
			}
		}
		return buildMsgWithLineNb(node, node, msg)
	}

	def private buildMsgWithLineNb(INode start, INode end, String msg) {
		val startLine = start.startLine
		val endLine = end.endLine
		if (startLine == endLine) {
			return "Line " + startLine + ": " + msg
		} else {
			return "Line " + startLine + "-" + endLine + ": " + msg
		}
	}
}
